### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Arnpd** [SwiftySpartan/Angular-1.5-cli#1]
Hi. How are you?
I added new component.
Then how can I create module for routing?
Thanks.

**Comment by andrewwormald** [comment]
Hi Antony,

Thank you for your email. Unfortunately development has stopped on this project due to Angular 1.x being traded in by many developers for Angular 2 / Angular 4. 

To create a module you will need to just do it the old school way by creating a new file and providing the right name and template inside.

I know this doesn’t help much and I apologies for not being of much help.

Andrew Wormald

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Tue, Aug 01, 2017 at 9:46 PM Antony Stefano

<
mailto:Antony Stefano <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi. How are you?

I added new component.

Then how can I create module for routing?

Thanks.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/SwiftySpartan/Angular-1.5-cli/issues/1
, or
